-- PAWA BAKERY outlet checklist schema + seed data
-- Generated from existing index.html storeData

DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS stores;

CREATE TABLE stores (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE categories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  store_id TEXT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  checklist_type TEXT NOT NULL CHECK (checklist_type IN ('opening','closing')),
  category_zh TEXT NOT NULL,
  category_en TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  zh TEXT NOT NULL,
  en TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0
);

INSERT INTO stores (id, name, sort_order) VALUES
  ('PLAZA_SING', 'PLAZA SING', 1),
  ('PLQ_MALL', 'PLQ MALL', 2),
  ('PLUS', 'PLUS', 3),
  ('STAR_VISTA', 'STAR VISTA', 4),
  ('SUNTEC_CITY', 'SUNTEC CITY', 5);

INSERT INTO categories (id, store_id, checklist_type, category_zh, category_en, sort_order) VALUES
  (1, 'PLAZA_SING', 'opening', '1. 设备开机 / Equipment Start Up', '1. 设备开机 / Equipment Start Up', 1),
  (2, 'PLAZA_SING', 'opening', '2. 物料准备 / Materials Preparation', '2. 物料准备 / Materials Preparation', 2),
  (3, 'PLAZA_SING', 'opening', '3. 营业准备 / Opening Preparation', '3. 营业准备 / Opening Preparation', 3),
  (4, 'PLAZA_SING', 'closing', '1. 店面清洁 / Store Cleaning', '1. 店面清洁 / Store Cleaning', 1),
  (5, 'PLAZA_SING', 'closing', '2. 设备及工具清洁 / Equipment and Tools Cleaning', '2. 设备及工具清洁 / Equipment and Tools Cleaning', 2),
  (6, 'PLAZA_SING', 'closing', '3. 次日准备 / Preparation for the Next Day', '3. 次日准备 / Preparation for the Next Day', 3),
  (7, 'PLAZA_SING', 'closing', '4. 关账及记录 / End Shift and Records', '4. 关账及记录 / End Shift and Records', 4),
  (8, 'PLAZA_SING', 'closing', '5. 收店收尾 / Closing Wrap Up', '5. 收店收尾 / Closing Wrap Up', 5),
  (9, 'PLQ_MALL', 'opening', '1. 设备开机 / Equipment Start Up', '1. 设备开机 / Equipment Start Up', 1),
  (10, 'PLQ_MALL', 'opening', '2. 物料准备 / Materials Preparation', '2. 物料准备 / Materials Preparation', 2),
  (11, 'PLQ_MALL', 'opening', '3. 营业准备 / Opening Preparation', '3. 营业准备 / Opening Preparation', 3),
  (12, 'PLQ_MALL', 'closing', '1. 店面清洁 / Store Cleaning', '1. 店面清洁 / Store Cleaning', 1),
  (13, 'PLQ_MALL', 'closing', '2. 设备及工具清洁 / Equipment and Tools Cleaning', '2. 设备及工具清洁 / Equipment and Tools Cleaning', 2),
  (14, 'PLQ_MALL', 'closing', '3. 次日准备 / Preparation for the Next Day', '3. 次日准备 / Preparation for the Next Day', 3),
  (15, 'PLQ_MALL', 'closing', '4. 关账及记录 / End Shift and Records', '4. 关账及记录 / End Shift and Records', 4),
  (16, 'PLQ_MALL', 'closing', '5. 收店收尾 / Closing Wrap Up', '5. 收店收尾 / Closing Wrap Up', 5),
  (17, 'PLUS', 'opening', '1. 设备开机 / Equipment Start Up', '1. 设备开机 / Equipment Start Up', 1),
  (18, 'PLUS', 'opening', '2. 物料准备 / Materials Preparation', '2. 物料准备 / Materials Preparation', 2),
  (19, 'PLUS', 'opening', '3. 店面整理 / Store Tidying', '3. 店面整理 / Store Tidying', 3),
  (20, 'PLUS', 'opening', '4. 营业准备 / Opening Preparation', '4. 营业准备 / Opening Preparation', 4),
  (21, 'PLUS', 'closing', '1. 店面清洁 / Store Cleaning', '1. 店面清洁 / Store Cleaning', 1),
  (22, 'PLUS', 'closing', '2. 设备及工具清洁 / Equipment and Tools Cleaning', '2. 设备及工具清洁 / Equipment and Tools Cleaning', 2),
  (23, 'PLUS', 'closing', '3. 次日准备 / Preparation for the Next Day', '3. 次日准备 / Preparation for the Next Day', 3),
  (24, 'PLUS', 'closing', '4. 关账及记录 / End Shift and Records', '4. 关账及记录 / End Shift and Records', 4),
  (25, 'PLUS', 'closing', '5. 收店收尾 / Closing Wrap Up', '5. 收店收尾 / Closing Wrap Up', 5),
  (26, 'STAR_VISTA', 'opening', '1. 设备开机 / Equipment Start Up', '1. 设备开机 / Equipment Start Up', 1),
  (27, 'STAR_VISTA', 'opening', '2. 物料准备 / Materials Preparation', '2. 物料准备 / Materials Preparation', 2),
  (28, 'STAR_VISTA', 'opening', '3. 营业准备 / Opening Preparation', '3. 营业准备 / Opening Preparation', 3),
  (29, 'STAR_VISTA', 'closing', '1. 店面清洁 / Store Cleaning', '1. 店面清洁 / Store Cleaning', 1),
  (30, 'STAR_VISTA', 'closing', '2. 设备及工具清洁 / Equipment and Tools Cleaning', '2. 设备及工具清洁 / Equipment and Tools Cleaning', 2),
  (31, 'STAR_VISTA', 'closing', '3. 关账及记录 / End Shift and Records', '3. 关账及记录 / End Shift and Records', 3),
  (32, 'STAR_VISTA', 'closing', '4. 次日准备 / Preparation for the Next Day', '4. 次日准备 / Preparation for the Next Day', 4),
  (33, 'STAR_VISTA', 'closing', '5. 收店收尾 / Closing Wrap Up', '5. 收店收尾 / Closing Wrap Up', 5),
  (34, 'SUNTEC_CITY', 'opening', '1. 设备开机 / Equipment Start Up', '1. 设备开机 / Equipment Start Up', 1),
  (35, 'SUNTEC_CITY', 'opening', '2. 物料准备 / Materials Preparation', '2. 物料准备 / Materials Preparation', 2),
  (36, 'SUNTEC_CITY', 'opening', '3. 营业准备 / Opening Preparation', '3. 营业准备 / Opening Preparation', 3),
  (37, 'SUNTEC_CITY', 'closing', '1. 店面清洁 / Store Cleaning', '1. 店面清洁 / Store Cleaning', 1),
  (38, 'SUNTEC_CITY', 'closing', '2. 设备及工具清洁 / Equipment and Tools Cleaning', '2. 设备及工具清洁 / Equipment and Tools Cleaning', 2),
  (39, 'SUNTEC_CITY', 'closing', '3. 次日准备 / Preparation for the Next Day', '3. 次日准备 / Preparation for the Next Day', 3),
  (40, 'SUNTEC_CITY', 'closing', '4. 关账及记录 / End Shift and Records', '4. 关账及记录 / End Shift and Records', 4),
  (41, 'SUNTEC_CITY', 'closing', '5. 收店收尾 / Closing Wrap Up', '5. 收店收尾 / Closing Wrap Up', 5);

INSERT INTO items (category_id, zh, en, sort_order) VALUES
  (1, '开启设备电源：POS、Terminal、面包柜灯。', 'Turn on equipment power: POS, terminal and bread cabinet light.', 1),
  (1, '清点备用金，并录入系统。', 'Count the float cash and enter it into the system.', 2),
  (1, '测试 POS 与 Terminal 连接是否正常。', 'Test that the POS and terminal connection works properly.', 3),
  (1, '擦干净收款台面和 EPOS 屏幕。', 'Wipe the cashier counter and EPOS screen clean.', 4),
  (2, '准备足够的面包袋和手提袋。', 'Prepare enough bread bags and carrier bags.', 1),
  (2, '准备 3 块新的湿一次性抹布。', 'Prepare 3 new disposable cloths and moisten them.', 2),
  (2, '将面包上架，并摆放价格标签。', 'Put bread on shelves and place price tags.', 3),
  (2, '清点预订单数量，并按订单预留。', 'Count pre order quantities and set them aside accordingly.', 4),
  (3, '按照片要求摆放面包和对应价格标签。', 'Place bread and matching price tags as shown in the Drive photos.', 1),
  (3, '10:30am 准时打开所有灯。', 'Turn on all lights promptly at 10:30am.', 2),
  (3, '收起 1 米线，摆好广告牌，准备营业。', 'Put away the 1 metre line, place advertising boards correctly and get ready for business.', 3),
  (4, '清洁面包柜：清面包屑、擦台面、更换油纸。', 'Clean the bread cabinet: remove crumbs, wipe the counter and replace parchment paper.', 1),
  (4, '用湿抹布和无尘布擦玻璃 2 遍。', 'Wipe glass twice using a wet cloth and lint free cloth.', 2),
  (4, '清洁货架物品，并摆放整齐。', 'Clean shelf items and arrange them neatly.', 3),
  (4, '按照片要求摆好价格标签。', 'Place price tags strictly according to the Drive photos.', 4),
  (4, '先扫地，再用加清洁剂的湿拖把拖地至少 2 遍。', 'Sweep the floor, then mop at least twice with detergent water.', 5),
  (5, '擦净面包盘和夹子并晾干；每周五彻底清洗。', 'Wipe bread trays and tongs clean and dry them. Wash thoroughly every Friday.', 1),
  (5, '擦净水槽，并倒掉垃圾。', 'Wipe the sink clean and dispose of rubbish.', 2),
  (6, '准备足够的次日包装材料。', 'Prepare enough packaging materials for the next day.', 1),
  (6, '按照片要求摆好次日价格标签。', 'Place next day price tags correctly according to the Drive photos.', 2),
  (6, '检查并订购缺少物料；周五下单。', 'Check and order missing materials. Order on Friday.', 3),
  (7, '将 staffmeal 和 waste 录入系统。', 'Enter staffmeal and waste into the system.', 1),
  (7, '清点钱箱，保留备用金，并将备用金金额写在当天销售总结小票上；现金差异需说明原因。', 'Count the cash drawer, keep the float cash and write the float amount on the daily sales summary receipt. Explain any cash difference.', 2),
  (7, '检查 POS 是否需要更新；如有新版本，立即更新后再关机。', 'Check whether POS needs an update. If a new version is available, update it before shutting down.', 3),
  (7, 'EPOS 完成 End Shift，并将当天销售总结小票拍照上传 Pawa Cashier group。', 'Complete End Shift in EPOS and upload a photo of the daily sales summary receipt to Pawa Cashier group.', 4),
  (7, '将多余现金存入公司账户，并上传存款小票照片至 Pawa Cashier group。', 'Deposit extra cash into the company account and upload the deposit receipt photo to Pawa Cashier group.', 5),
  (7, '将重要物品锁在抽屉里，并藏好抽屉钥匙。', 'Lock important items in the drawer and hide the drawer key properly.', 6),
  (7, '关闭空调、风扇、灯、音响、电子屏和 POS 电源；保留 Wi Fi 和招牌灯电源，按照片执行。', 'Turn off air conditioner, fan, lights, speaker, digital screen and POS. Keep Wi Fi and sign lights on, following the Drive photos.', 7),
  (8, '收好广告牌。', 'Put away the advertising boards.', 1),
  (8, '将一米线围栏整齐拉到正确位置。', 'Pull the rope barrier neatly to the correct position.', 2),
  (8, '拍照上传：面包柜含价格标签、地面、台面、店面整体。', 'Upload photos of the bread cabinet with price tags, floor, counter and overall store to Pawa Cashier group.', 3),
  (9, '开启设备电源：POS、Terminal、面包柜灯。', 'Turn on equipment power: POS, terminal and bread cabinet light.', 1),
  (9, '清点备用金，并录入系统。', 'Count the float cash and enter it into the system.', 2),
  (9, '测试 POS 与 Terminal 连接是否正常。', 'Test that the POS and terminal connection works properly.', 3),
  (9, '擦干净收款台面和 EPOS 屏幕。', 'Wipe the cashier counter and EPOS screen clean.', 4),
  (10, '准备足够的面包袋和手提袋。', 'Prepare enough bread bags and carrier bags.', 1),
  (10, '准备 3 块新的湿一次性抹布。', 'Prepare 3 new disposable cloths and moisten them.', 2),
  (10, '将面包上架，并摆放价格标签。', 'Put bread on shelves and place price tags.', 3),
  (10, '清点预订单数量，并按订单预留。', 'Count pre order quantities and set them aside accordingly.', 4),
  (11, '按照片要求摆放面包和对应价格标签。', 'Place bread and matching price tags as shown in the Drive photos.', 1),
  (11, '9:30am 准时打开所有灯。', 'Turn on all lights promptly at 9:30am.', 2),
  (11, '收起 1 米线，摆好广告牌，准备营业。', 'Put away the 1 metre line, place advertising boards correctly and get ready for business.', 3),
  (12, '清洁面包柜：清面包屑、擦台面、更换油纸。', 'Clean the bread cabinet: remove crumbs, wipe the counter and replace parchment paper.', 1),
  (12, '用湿抹布和无尘布擦玻璃 2 遍。', 'Wipe glass twice using a wet cloth and lint free cloth.', 2),
  (12, '清洁货架物品，并摆放整齐。', 'Clean shelf items and arrange them neatly.', 3),
  (12, '按照片要求摆好价格标签。', 'Place price tags strictly according to the Drive photos.', 4),
  (12, '先扫地，再用加清洁剂的湿拖把拖地至少 2 遍。', 'Sweep the floor, then mop at least twice with detergent water.', 5),
  (13, '擦净面包盘和夹子并晾干；每周五彻底清洗。', 'Wipe bread trays and tongs clean and dry them. Wash thoroughly every Friday.', 1),
  (13, '擦净水槽，并倒掉垃圾。', 'Wipe the sink clean and dispose of rubbish.', 2),
  (14, '准备足够的次日包装材料。', 'Prepare enough packaging materials for the next day.', 1),
  (14, '按照片要求摆好次日价格标签。', 'Place next day price tags correctly according to the Drive photos.', 2),
  (14, '检查并订购缺少物料；周五下单。', 'Check and order missing materials. Order on Friday.', 3),
  (15, '将 staffmeal 和 waste 录入系统。', 'Enter staffmeal and waste into the system.', 1),
  (15, '清点钱箱，保留备用金，并将备用金金额写在当天销售总结小票上；现金差异需说明原因。', 'Count the cash drawer, keep the float cash and write the float amount on the daily sales summary receipt. Explain any cash difference.', 2),
  (15, '检查 POS 是否需要更新；如有新版本，立即更新后再关机。', 'Check whether POS needs an update. If a new version is available, update it before shutting down.', 3),
  (15, 'EPOS 完成 End Shift，并将当天销售总结小票拍照上传 Pawa Cashier group。', 'Complete End Shift in EPOS and upload a photo of the daily sales summary receipt to Pawa Cashier group.', 4),
  (15, '将多余现金存入公司账户，并上传存款小票照片至 Pawa Cashier group。', 'Deposit extra cash into the company account and upload the deposit receipt photo to Pawa Cashier group.', 5),
  (15, '将重要物品锁在抽屉里，并藏好抽屉钥匙。', 'Lock important items in the drawer and hide the drawer key properly.', 6),
  (15, '关闭空调、风扇、灯、音响、电子屏和 POS 电源；保留 Wi Fi 和招牌灯电源，按照片执行。', 'Turn off air conditioner, fan, lights, speaker, digital screen and POS. Keep Wi Fi and sign lights on, following the Drive photos.', 7),
  (16, '收好广告牌。', 'Put away the advertising boards.', 1),
  (16, '将绳带围栏整齐拉到正确位置。', 'Pull the rope barrier neatly to the correct position.', 2),
  (16, '拍照上传：面包柜含价格标签、地面、台面、店面整体。', 'Upload photos of the bread cabinet with price tags, floor, counter and overall store to Pawa Cashier group.', 3),
  (17, '开启设备电源：POS、刷卡机、小冰箱、音响、面包柜灯和风扇。', 'Turn on equipment power: POS, card machine, small refrigerator, speaker, bread cabinet lights and fans.', 1),
  (17, '清点备用金，并录入系统。', 'Count the float cash and enter it into the system.', 2),
  (17, '测试 POS 与 Terminal 连接是否正常。', 'Test that the POS and terminal connection works properly.', 3),
  (17, '连接音响，并用 iPad 播放英文歌曲。', 'Connect the speaker and play English songs on the iPad.', 4),
  (18, '准备足够的面包袋和手提袋。', 'Prepare enough bread bags and carrier bags.', 1),
  (18, '准备 4 块新的湿一次性抹布。', 'Prepare 4 new disposable cloths and moisten them.', 2),
  (18, '清点预订单数量，并按订单预留。', 'Count pre order quantities and set them aside accordingly.', 3),
  (19, '擦干净收款台面和 EPOS 屏幕。', 'Wipe the cashier counter and EPOS screen clean.', 1),
  (19, '将广告牌摆放到正确位置。', 'Place advertising boards in the correct position.', 2),
  (19, '整理饼干并擦拭干净。', 'Arrange the cookies neatly and wipe them clean.', 3),
  (20, '按照片要求将面包放到正确货架位置，并摆好对应价格标签。', 'Place bread and matching price tags correctly according to the Drive photos.', 1),
  (20, '8:00am 准时打开所有灯。', 'Turn on all lights promptly at 8:00am.', 2),
  (20, '开门，并将门状态设为 OPEN。', 'Open the door and set the door status to OPEN.', 3),
  (21, '清洁面包柜：清面包屑、擦台面、更换油纸。', 'Clean the bread cabinet: remove crumbs, wipe the counter and replace parchment paper.', 1),
  (21, '用无油湿抹布和无尘布擦面包柜玻璃 2 遍。', 'Wipe bread cabinet glass twice using an oil free wet cloth and lint free cloth.', 2),
  (21, '清洁货架物品，并摆放整齐。', 'Clean shelf items and arrange them neatly.', 3),
  (21, '按照片要求摆好价格标签。', 'Place price tags strictly according to the Drive photos.', 4),
  (21, '先扫地，再用加清洁剂的湿拖把拖地至少 2 遍。', 'Sweep the floor, then mop at least twice with detergent water.', 5),
  (22, '清洗所有铁面包盘并晾干。', 'Wash all iron bread trays and dry them.', 1),
  (22, '擦净面包盘和夹子；每周五彻底清洗所有盘子和夹子。', 'Wipe bread trays and tongs clean. Wash all trays and tongs thoroughly every Friday.', 2),
  (22, '清洁切片机，并擦干。', 'Clean the slicer and wipe it dry.', 3),
  (22, '擦净水槽，并倒掉垃圾。', 'Wipe the sink clean and dispose of rubbish.', 4),
  (23, '准备足够的次日包装材料。', 'Prepare enough packaging materials for the next day.', 1),
  (23, '检查并订购缺少物料；周五下单。', 'Check and order missing materials. Order on Friday.', 2),
  (24, '确认所有 staffmeal 和 waste 已录入系统。', 'Make sure all staffmeal and waste are entered into the system.', 1),
  (24, '清点钱箱，保留备用金，并将备用金金额写在当天销售总结小票上；现金差异需说明原因。', 'Count the cash drawer, keep the float cash and write the float amount on the daily sales summary receipt. Explain any cash difference.', 2),
  (24, '检查 POS 是否需要更新；如有新版本，立即更新后再关机。', 'Check whether POS needs an update. If a new version is available, update it before shutting down.', 3),
  (24, 'EPOS 完成 End Shift，并将当天销售总结小票拍照上传 Pawa Cashier group。', 'Complete End Shift in EPOS and upload a photo of the daily sales summary receipt to Pawa Cashier group.', 4),
  (24, '将多余现金存入公司账户，并上传存款小票照片至 Pawa Cashier group。', 'Deposit extra cash into the company account and upload the deposit receipt photo to Pawa Cashier group.', 5),
  (25, '关闭空调、风扇、灯、音响、电子屏和 POS 电源；保留 Wi Fi 电源，按照片执行。', 'Turn off air conditioner, fan, lights, speaker, digital screen and POS. Keep Wi Fi on, following the Drive photos.', 1),
  (25, '收好广告牌；每周五收到店内。', 'Put away advertising boards. Bring them into the shop on Friday.', 2),
  (25, '拍照上传：面包柜含价格标签、地面、台面、店面整体。', 'Upload photos of the bread cabinet with price tags, floor, counter and overall store to Pawa Cashier group.', 3),
  (25, '关门，将门状态设为 LOCK，并把钥匙放入门口木盒。', 'Close the door, set the door status to LOCK and put the key in the wooden box at the door gate.', 4),
  (26, '开启设备电源：POS、刷卡机、咖啡机、面包柜和灯光。', 'Turn on equipment power: POS, card machine, coffee machine, bread cabinet and lights.', 1),
  (26, '清点备用金，并录入系统。', 'Count the float cash and enter it into the system.', 2),
  (26, '测试 POS 与 Terminal 连接是否正常。', 'Test that the POS and terminal connection works properly.', 3),
  (26, '擦干净收款台面和 EPOS 屏幕。', 'Wipe the cashier counter and EPOS screen clean.', 4),
  (26, '打开音响，连接手机蓝牙，播放英文音乐。', 'Turn on the speaker, connect phone Bluetooth and play English music.', 5),
  (27, '确认面包袋、大号和小号手提袋充足。', 'Make sure bread bags and large and small carrier bags are sufficient.', 1),
  (27, '确认磨豆机咖啡豆、咖啡杯和杯盖等物料充足。', 'Make sure coffee beans in the grinder, coffee cups, lids and related materials are sufficient.', 2),
  (27, '确认茶包、果酱、冷柜牛奶和直饮冰水充足。', 'Make sure tea bags, jam, chilled milk and drinking ice water are sufficient.', 3),
  (28, '摆整齐桌椅，并确认桌面和椅面干净。', 'Arrange tables and chairs neatly, and make sure table tops and chair surfaces are clean.', 1),
  (28, '收起 1 米线，摆好广告牌，并压住广告牌支架底部防风。', 'Put away the 1 metre line, place advertising boards correctly and weigh down the stand base to prevent wind.', 2),
  (28, '面包上架并放到正确位置，确认价格牌无缺失。', 'Put bread on shelves in the correct positions and make sure no price tags are missing.', 3),
  (28, '打开 Grab Terminal，设置可售卖的面包和数量。', 'Turn on Grab Terminal and set the available bread items and quantities.', 4),
  (29, '清洁面包柜：清面包屑、擦台面、更换油纸。', 'Clean the bread cabinet: remove crumbs, wipe the counter and replace parchment paper.', 1),
  (29, '用无油湿抹布和无尘布擦面包柜玻璃 2 遍。', 'Wipe bread cabinet glass twice using an oil free wet cloth and lint free cloth.', 2),
  (29, '按位置要求摆好价格标签。', 'Place price tags strictly in the required positions.', 3),
  (29, '倒掉蛋糕柜积水盒，并关闭电源。', 'Empty the cake cabinet water tray and turn off the power.', 4),
  (29, '将椅子倒放在桌面上；先扫地，再用加清洁剂的湿拖把拖干净。', 'Place chairs upside down on tables. Sweep the floor, then mop with detergent water.', 5),
  (30, '按流程清洁咖啡机。', 'Clean the coffee machine according to the procedure.', 1),
  (30, '擦净水槽，并倒掉垃圾。', 'Wipe the sink clean and dispose of rubbish.', 2),
  (30, '擦净面包盘和夹子；每周五用洗洁精全部清洗并晾干。', 'Wipe bread trays and tongs clean. Every Friday, wash all trays and tongs with detergent and dry them.', 3),
  (31, '确认所有 staffmeal 和 waste 已录入系统。', 'Make sure all staffmeal and waste are entered into the system.', 1),
  (31, '清点钱箱，保留备用金，并将备用金金额写在当天销售总结小票上；现金差异需说明原因。', 'Count the cash drawer, keep the float cash and write the float amount on the daily sales summary receipt. Explain any cash difference.', 2),
  (31, '将多余现金包好并锁进抽屉，记录当天现金金额到现金记录表，并截图上传 Pawa Cashier group。', 'Wrap extra cash and lock it in the drawer. Record the daily cash amount in the cash record sheet and upload a screenshot to Pawa Cashier group.', 3),
  (31, 'EPOS 完成 End Shift，并将当天销售总结小票拍照上传 Pawa Cashier group。', 'Complete End Shift in EPOS and upload a photo of the daily sales summary receipt to Pawa Cashier group.', 4),
  (31, '拍照上传 Grab Terminal 当天销售金额至 Pawa Cashier group。', 'Take a photo of the Grab Terminal daily sales amount and upload it to Pawa Cashier group.', 5),
  (31, '将客服手机和重要物品锁在抽屉里，并藏好抽屉钥匙。', 'Lock the customer service phone and important items in the drawer, and hide the drawer key properly.', 6),
  (31, '关闭空调、风扇、灯、音响、电子屏和 POS 电源；保留 Wi Fi 和招牌灯电源，按照片执行。', 'Turn off air conditioner, fan, lights, speaker, digital screen and POS. Keep Wi Fi and sign lights on, following the Drive photos.', 7),
  (32, '准备足够的次日包装材料。', 'Prepare enough packaging materials for the next day.', 1),
  (32, '检查并订购缺少物料；周一、周三、周五下单。', 'Check and order missing materials on Monday, Wednesday and Friday.', 2),
  (32, '给音响设备充电。', 'Charge the audio equipment.', 3),
  (33, '收好广告牌，放在餐盘回收处桌面上并压好，防止夜间被风吹走。', 'Put away advertising boards on the tray return table and weigh them down to prevent wind at night.', 1),
  (33, '用桌子和 1 米线围好门店，防止陌生人进入。', 'Use tables and the 1 metre line to block the store and prevent strangers from entering.', 2),
  (33, '拍照上传：面包柜含价格标签、咖啡机、桌椅、地面、台面、店面整体。', 'Upload photos of the bread cabinet with price tags, coffee machine, tables and chairs, floor, counter and overall store to Pawa Cashier group.', 3),
  (34, '开启设备电源：POS、刷卡机、咖啡机、面包柜和灯光。', 'Turn on equipment power: POS, card machine, coffee machine, bread cabinet and lights.', 1),
  (34, '清点备用金，并录入系统。', 'Count the float cash and enter it into the system.', 2),
  (34, '测试 POS 与 Terminal 连接是否正常。', 'Test that the POS and terminal connection works properly.', 3),
  (34, '擦干净收款台面和 EPOS 屏幕。', 'Wipe the cashier counter and EPOS screen clean.', 4),
  (35, '确认面包袋、大号和小号手提袋充足。', 'Make sure bread bags and large and small carrier bags are sufficient.', 1),
  (35, '确认磨豆机咖啡豆、咖啡杯和杯盖等物料充足。', 'Make sure coffee beans in the grinder, coffee cups, lids and related materials are sufficient.', 2),
  (35, '确认茶包、果酱、小冰箱牛奶和直饮冰水充足。', 'Make sure tea bags, jam, small refrigerator milk and drinking ice water are sufficient.', 3),
  (35, '准备 4 块一次性湿抹布。', 'Prepare 4 disposable wet cloths.', 4),
  (36, '收起 1 米线，并将广告牌摆放到正确位置。', 'Put away the 1 metre line and place advertising boards correctly.', 1),
  (36, '面包上架并放到正确位置，确认价格牌无缺失。', 'Put bread on shelves in the correct positions and make sure no price tags are missing.', 2),
  (37, '清洁面包柜：清面包屑、擦台面、更换油纸。', 'Clean the bread cabinet: remove crumbs, wipe the counter and replace parchment paper.', 1),
  (37, '用无油湿抹布和无尘布擦面包柜玻璃 2 遍。', 'Wipe bread cabinet glass twice using an oil free wet cloth and lint free cloth.', 2),
  (37, '清洁货架物品，并摆放整齐。', 'Clean shelf items and arrange them neatly.', 3),
  (37, '按照片要求摆好价格标签。', 'Place price tags strictly according to the Drive photos.', 4),
  (37, '先扫地，再用加清洁剂的湿拖把拖地至少 2 遍。', 'Sweep the floor, then mop at least twice with detergent water.', 5),
  (38, '按流程清洁咖啡机。', 'Clean the coffee machine according to the procedure.', 1),
  (38, '擦净水槽，并倒掉垃圾。', 'Wipe the sink clean and dispose of rubbish.', 2),
  (38, '擦净面包盘和夹子；每周五用洗洁精全部清洗并晾干。', 'Wipe bread trays and tongs clean. Every Friday, wash all trays and tongs with detergent and dry them.', 3),
  (39, '准备足够的次日包装材料。', 'Prepare enough packaging materials for the next day.', 1),
  (39, '检查并订购缺少物料；周一、周三、周五下单。', 'Check and order missing materials on Monday, Wednesday and Friday.', 2),
  (39, '给音响设备充电。', 'Charge the audio equipment.', 3),
  (40, '确认所有 staffmeal 和 waste 已录入系统。', 'Make sure all staffmeal and waste are entered into the system.', 1),
  (40, '清点钱箱，保留备用金，并将备用金金额写在当天销售总结小票上；现金差异需说明原因。', 'Count the cash drawer, keep the float cash and write the float amount on the daily sales summary receipt. Explain any cash difference.', 2),
  (40, '检查 POS 是否需要更新；如有新版本，立即更新后再关机。', 'Check whether POS needs an update. If a new version is available, update it before shutting down.', 3),
  (40, 'EPOS 完成 End Shift，并将当天销售总结小票拍照上传 Pawa Cashier group。', 'Complete End Shift in EPOS and upload a photo of the daily sales summary receipt to Pawa Cashier group.', 4),
  (40, '将多余现金存入公司账户，并上传存款小票照片至 Pawa Cashier group。', 'Deposit extra cash into the company account and upload the deposit receipt photo to Pawa Cashier group.', 5),
  (40, '将重要物品锁在抽屉里，并藏好抽屉钥匙。', 'Lock important items in the drawer and hide the drawer key properly.', 6),
  (40, '关闭空调、风扇、灯、音响、电子屏和 POS 电源；保留 Wi Fi 和招牌灯电源，按照片执行。', 'Turn off air conditioner, fan, lights, speaker, digital screen and POS. Keep Wi Fi and sign lights on, following the Drive photos.', 7),
  (41, '收好广告牌和 1 米线，并放到正确位置。', 'Put away advertising boards and the 1 metre line, and place them correctly.', 1),
  (41, '用面包架子车挡住进出口，防止陌生人进入。', 'Use the bread rack trolley to block the entrance and exit to prevent strangers from entering.', 2),
  (41, '拍照上传：面包柜含价格标签、咖啡机、桌椅、地面、台面、店面整体。', 'Upload photos of the bread cabinet with price tags, coffee machine, tables and chairs, floor, counter and overall store to Pawa Cashier group.', 3);
